<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class Permissoes
    Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim TreeNode1 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Clientes")
        Dim TreeNode2 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Região")
        Dim TreeNode3 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ver Limite de Crédito")
        Dim TreeNode4 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório Cliente")
        Dim TreeNode5 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Clientes", New System.Windows.Forms.TreeNode() {TreeNode1, TreeNode2, TreeNode3, TreeNode4})
        Dim TreeNode6 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Agenda Serviço e Compromisso")
        Dim TreeNode7 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Cep")
        Dim TreeNode8 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Fornecedor")
        Dim TreeNode9 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório Fornecedor")
        Dim TreeNode10 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Fornecedores", New System.Windows.Forms.TreeNode() {TreeNode8, TreeNode9})
        Dim TreeNode11 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Produtos")
        Dim TreeNode12 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Produtos")
        Dim TreeNode13 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Produtos Inativos")
        Dim TreeNode14 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta de Estoque de Produtos")
        Dim TreeNode15 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Atualizador Estoque")
        Dim TreeNode16 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ajuste do Estoque")
        Dim TreeNode17 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Atualizar Tributação Pis - Cofins Venda")
        Dim TreeNode18 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Tranferência de Estoque (Depósito/Venda)")
        Dim TreeNode19 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Grupos")
        Dim TreeNode20 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Marcas")
        Dim TreeNode21 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Cor")
        Dim TreeNode22 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Tipo de Grupo")
        Dim TreeNode23 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de SubGrupo")
        Dim TreeNode24 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Localização")
        Dim TreeNode25 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de Produto")
        Dim TreeNode26 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de Cadastro Gerais")
        Dim TreeNode27 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Saldo de Estoque")
        Dim TreeNode28 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Etiquetas de Produto - Cod Barra")
        Dim TreeNode29 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Iventário")
        Dim TreeNode30 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Gerar Etiquetas")
        Dim TreeNode31 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Produtos", New System.Windows.Forms.TreeNode() {TreeNode11, TreeNode12, TreeNode13, TreeNode14, TreeNode15, TreeNode16, TreeNode17, TreeNode18, TreeNode19, TreeNode20, TreeNode21, TreeNode22, TreeNode23, TreeNode24, TreeNode25, TreeNode26, TreeNode27, TreeNode28, TreeNode29, TreeNode30})
        Dim TreeNode32 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ordem de Produção")
        Dim TreeNode33 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Confirma Ordem de Produção")
        Dim TreeNode34 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Produção", New System.Windows.Forms.TreeNode() {TreeNode32, TreeNode33})
        Dim TreeNode35 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Objetos(Veículos)")
        Dim TreeNode36 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Localiza Veículos por placa")
        Dim TreeNode37 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Serviços")
        Dim TreeNode38 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Funcionário e Serviço")
        Dim TreeNode39 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Grupo de Serviço")
        Dim TreeNode40 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta Preço de Serviço")
        Dim TreeNode41 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Alteração de Preço de Serviço")
        Dim TreeNode42 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Serviços", New System.Windows.Forms.TreeNode() {TreeNode35, TreeNode36, TreeNode37, TreeNode38, TreeNode39, TreeNode40, TreeNode41})
        Dim TreeNode43 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Local de Pagamento")
        Dim TreeNode44 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Condição de Pagamento")
        Dim TreeNode45 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Tipo de Pagamento")
        Dim TreeNode46 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Anexar Cond. Pgto ao Tipo de Pgto")
        Dim TreeNode47 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Cfop")
        Dim TreeNode48 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro CFOP Entrada e Saída")
        Dim TreeNode49 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Transportadora")
        Dim TreeNode50 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastros Gerais", New System.Windows.Forms.TreeNode() {TreeNode43, TreeNode44, TreeNode45, TreeNode46, TreeNode47, TreeNode48, TreeNode49})
        Dim TreeNode51 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Empresa")
        Dim TreeNode52 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Exportação para NFE")
        Dim TreeNode53 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Exportação para Paf")
        Dim TreeNode54 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Exporta Paf Exclaim")
        Dim TreeNode55 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Exporta Prosoft")
        Dim TreeNode56 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Geral", New System.Windows.Forms.TreeNode() {TreeNode5, TreeNode6, TreeNode7, TreeNode10, TreeNode31, TreeNode34, TreeNode42, TreeNode50, TreeNode51, TreeNode52, TreeNode53, TreeNode54, TreeNode55})
        Dim TreeNode57 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Prorrogação contas a Receber")
        Dim TreeNode58 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Alterar Local de Pagamento")
        Dim TreeNode59 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Alterar Data de Vencimento")
        Dim TreeNode60 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta/Baixa de Contas a Receber", New System.Windows.Forms.TreeNode() {TreeNode57, TreeNode58, TreeNode59})
        Dim TreeNode61 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Baixa Recebimento em Lote")
        Dim TreeNode62 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Agrupar Recebimentos")
        Dim TreeNode63 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("A Receber Avulso")
        Dim TreeNode64 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de Contas a Receber")
        Dim TreeNode65 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Contas a Receber no Período e Valor")
        Dim TreeNode66 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Consulta/Baixa de Contas a Pagar")
        Dim TreeNode67 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de consta a Pagar")
        Dim TreeNode68 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Recibo Avulso")
        Dim TreeNode69 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Emitir Duplicata Avulso")
        Dim TreeNode70 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Reimpressão Recibo Pagar e Receber")
        Dim TreeNode71 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Editar contas a Pagar")
        Dim TreeNode72 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Central Cartão")
        Dim TreeNode73 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Editar Parcelamento Contas a Pagar")
        Dim TreeNode74 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Pagar e Receber", New System.Windows.Forms.TreeNode() {TreeNode60, TreeNode61, TreeNode62, TreeNode63, TreeNode64, TreeNode65, TreeNode66, TreeNode67, TreeNode68, TreeNode69, TreeNode70, TreeNode71, TreeNode72, TreeNode73})
        Dim TreeNode75 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Senha desconto produto")
        Dim TreeNode76 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pedido", New System.Windows.Forms.TreeNode() {TreeNode75})
        Dim TreeNode77 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ordem de Serviço")
        Dim TreeNode78 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Historico Cliente Os Pedido")
        Dim TreeNode79 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pesquisa de Pedido")
        Dim TreeNode80 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Reimpressão de Pedido")
        Dim TreeNode81 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Acompanhamento de Pedido")
        Dim TreeNode82 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cancelamento de Pedido")
        Dim TreeNode83 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios de Pedido")
        Dim TreeNode84 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios de Pedido OS")
        Dim TreeNode85 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório de Comissão Vendedores")
        Dim TreeNode86 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios Pedido", New System.Windows.Forms.TreeNode() {TreeNode83, TreeNode84, TreeNode85})
        Dim TreeNode87 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cancelamento de Ordem de Embarque")
        Dim TreeNode88 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Orçamento")
        Dim TreeNode89 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Orçamento de Serviços e Produtos")
        Dim TreeNode90 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Nota Fiscal del Serviço")
        Dim TreeNode91 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Configuração de Nota Fiscal de Serviço")
        Dim TreeNode92 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Nota Fiscal", New System.Windows.Forms.TreeNode() {TreeNode90, TreeNode91})
        Dim TreeNode93 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Entrada de Documentos")
        Dim TreeNode94 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Entrada de Estoque")
        Dim TreeNode95 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios de NF Compras")
        Dim TreeNode96 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Entrada", New System.Windows.Forms.TreeNode() {TreeNode93, TreeNode94, TreeNode95})
        Dim TreeNode97 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Movimento", New System.Windows.Forms.TreeNode() {TreeNode76, TreeNode77, TreeNode78, TreeNode79, TreeNode80, TreeNode81, TreeNode82, TreeNode86, TreeNode87, TreeNode88, TreeNode89, TreeNode92, TreeNode96})
        Dim TreeNode98 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Documento de Entrada")
        Dim TreeNode99 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Entrada Nota Fiscal")
        Dim TreeNode100 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pedido Compra")
        Dim TreeNode101 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pedido Compra Financeiro")
        Dim TreeNode102 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Movimento Sellshoes", New System.Windows.Forms.TreeNode() {TreeNode98, TreeNode99, TreeNode100, TreeNode101})
        Dim TreeNode103 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ativar e Desativar Caixa")
        Dim TreeNode104 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Visualizador do Caixa")
        Dim TreeNode105 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Repasse Cheque Pré do Caixa")
        Dim TreeNode106 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Lançamentos Caixa")
        Dim TreeNode107 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Lançamento de Crédito p/Cliente")
        Dim TreeNode108 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Impressão de  NP/Duplicata do Pedido")
        Dim TreeNode109 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Estorno Recebimento")
        Dim TreeNode110 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Estorno de Pagamento")
        Dim TreeNode111 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatório")
        Dim TreeNode112 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Conta Balancete")
        Dim TreeNode113 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Conta Resultado")
        Dim TreeNode114 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Mostrar Contas Resultado Inativas")
        Dim TreeNode115 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Reclassificar Contas")
        Dim TreeNode116 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios")
        Dim TreeNode117 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Balancete Orçamentário", New System.Windows.Forms.TreeNode() {TreeNode116})
        Dim TreeNode118 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Bancos")
        Dim TreeNode119 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro Conta Corrente")
        Dim TreeNode120 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Conta Corrente/Bancos", New System.Windows.Forms.TreeNode() {TreeNode118, TreeNode119})
        Dim TreeNode121 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Central de Conta Corrente")
        Dim TreeNode122 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Lançamento Banco")
        Dim TreeNode123 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Conta Corrente")
        Dim TreeNode124 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Extrato Banco")
        Dim TreeNode125 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Compensar Cheque")
        Dim TreeNode126 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cheque-Pré - Clientes")
        Dim TreeNode127 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cheque-Pré - Devolvidos")
        Dim TreeNode128 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatórios Cheque Pré")
        Dim TreeNode129 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Contrato")
        Dim TreeNode130 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Caixa e Banco", New System.Windows.Forms.TreeNode() {TreeNode103, TreeNode104, TreeNode105, TreeNode106, TreeNode107, TreeNode108, TreeNode109, TreeNode110, TreeNode111, TreeNode112, TreeNode113, TreeNode114, TreeNode115, TreeNode117, TreeNode120, TreeNode121, TreeNode122, TreeNode123, TreeNode124, TreeNode125, TreeNode126, TreeNode127, TreeNode128, TreeNode129})
        Dim TreeNode131 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Funcionários")
        Dim TreeNode132 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cartão de Funcionário")
        Dim TreeNode133 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Departamentos")
        Dim TreeNode134 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Profissão")
        Dim TreeNode135 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Funcionários")
        Dim TreeNode136 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Departamentos")
        Dim TreeNode137 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Profissão")
        Dim TreeNode138 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Relatorios de Funcionários", New System.Windows.Forms.TreeNode() {TreeNode135, TreeNode136, TreeNode137})
        Dim TreeNode139 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu RH", New System.Windows.Forms.TreeNode() {TreeNode131, TreeNode132, TreeNode133, TreeNode134, TreeNode138})
        Dim TreeNode140 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Permissões")
        Dim TreeNode141 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Gerenciador de Permissões")
        Dim TreeNode142 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Auditoria")
        Dim TreeNode143 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("UserSenha")
        Dim TreeNode144 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Cadastro de Caixa")
        Dim TreeNode145 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Caixa em Aberto")
        Dim TreeNode146 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Criar e Fechar Dia de Trabalho")
        Dim TreeNode147 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Gerar Código de Segurança do Dia")
        Dim TreeNode148 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Configuração do Banco de Dados (Alternar)")
        Dim TreeNode149 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Atualizar Tabelas")
        Dim TreeNode150 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Sobre")
        Dim TreeNode151 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Configurações", New System.Windows.Forms.TreeNode() {TreeNode140, TreeNode141, TreeNode142, TreeNode143, TreeNode144, TreeNode145, TreeNode146, TreeNode147, TreeNode148, TreeNode149, TreeNode150})
        Dim TreeNode152 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("----------------------------------")
        Dim TreeNode153 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ver Pendências")
        Dim TreeNode154 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Ver Ultimas Vendas")
        Dim TreeNode155 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pesquisa de Cliente", New System.Windows.Forms.TreeNode() {TreeNode153, TreeNode154})
        Dim TreeNode156 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Pesquisa de Produto")
        Dim TreeNode157 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Reimpressão Pedido")
        Dim TreeNode158 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Vendas")
        Dim TreeNode159 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Devolução")
        Dim TreeNode160 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Orçamento")
        Dim TreeNode161 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Inicira Caixa")
        Dim TreeNode162 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Vizualizar Caixa")
        Dim TreeNode163 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Finalizar Vendas")
        Dim TreeNode164 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Recebimento")
        Dim TreeNode165 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Recebimento em Lote")
        Dim TreeNode166 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Resumo de Vendas")
        Dim TreeNode167 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Auxiliar SellShoes", New System.Windows.Forms.TreeNode() {TreeNode155, TreeNode156, TreeNode157, TreeNode158, TreeNode159, TreeNode160, TreeNode161, TreeNode162, TreeNode163, TreeNode164, TreeNode165, TreeNode166})
        Dim TreeNode168 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Permissão desc. Vendas")
        Dim TreeNode169 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Banco Compensar")
        Dim TreeNode170 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Codigo de Segurança")
        Dim TreeNode171 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Menu Interno", New System.Windows.Forms.TreeNode() {TreeNode168, TreeNode169, TreeNode170})
        Dim TreeNode172 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Permissão", New System.Windows.Forms.TreeNode() {TreeNode56, TreeNode74, TreeNode97, TreeNode102, TreeNode130, TreeNode139, TreeNode151, TreeNode152, TreeNode167, TreeNode171})
        Me.PanelEx1 = New DevComponents.DotNetBar.PanelEx()
        Me.btCopiarDe = New DevComponents.DotNetBar.ButtonX()
        Me.btFechar = New DevComponents.DotNetBar.ButtonX()
        Me.ListaPermissao = New System.Windows.Forms.TreeView()
        Me.MenuAdicional = New System.Windows.Forms.ContextMenuStrip(Me.components)
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem = New System.Windows.Forms.ToolStripMenuItem()
        Me.HelpProvider1 = New System.Windows.Forms.HelpProvider()
        Me.PanelEx1.SuspendLayout()
        Me.MenuAdicional.SuspendLayout()
        Me.SuspendLayout()
        '
        'PanelEx1
        '
        Me.PanelEx1.CanvasColor = System.Drawing.SystemColors.Control
        Me.PanelEx1.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.StyleManagerControlled
        Me.PanelEx1.Controls.Add(Me.btCopiarDe)
        Me.PanelEx1.Controls.Add(Me.btFechar)
        Me.PanelEx1.Controls.Add(Me.ListaPermissao)
        Me.PanelEx1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.PanelEx1.Location = New System.Drawing.Point(0, 0)
        Me.PanelEx1.Name = "PanelEx1"
        Me.PanelEx1.Size = New System.Drawing.Size(481, 426)
        Me.PanelEx1.Style.Alignment = System.Drawing.StringAlignment.Center
        Me.PanelEx1.Style.BackColor1.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground
        Me.PanelEx1.Style.BackColor2.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2
        Me.PanelEx1.Style.Border = DevComponents.DotNetBar.eBorderType.SingleLine
        Me.PanelEx1.Style.BorderColor.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder
        Me.PanelEx1.Style.ForeColor.ColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText
        Me.PanelEx1.Style.GradientAngle = 90
        Me.PanelEx1.TabIndex = 1
        '
        'btCopiarDe
        '
        Me.btCopiarDe.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton
        Me.btCopiarDe.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground
        Me.btCopiarDe.Location = New System.Drawing.Point(12, 396)
        Me.btCopiarDe.Name = "btCopiarDe"
        Me.btCopiarDe.Size = New System.Drawing.Size(169, 23)
        Me.btCopiarDe.TabIndex = 16
        Me.btCopiarDe.Text = "Copiar permissões de Usuário"
        '
        'btFechar
        '
        Me.btFechar.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton
        Me.btFechar.ColorTable = DevComponents.DotNetBar.eButtonColor.OrangeWithBackground
        Me.btFechar.Location = New System.Drawing.Point(396, 396)
        Me.btFechar.Name = "btFechar"
        Me.btFechar.Size = New System.Drawing.Size(75, 23)
        Me.btFechar.TabIndex = 15
        Me.btFechar.Text = "Fechar"
        '
        'ListaPermissao
        '
        Me.ListaPermissao.ContextMenuStrip = Me.MenuAdicional
        Me.ListaPermissao.Location = New System.Drawing.Point(12, 12)
        Me.ListaPermissao.Name = "ListaPermissao"
        TreeNode1.Name = "Clientes"
        TreeNode1.Tag = "S"
        TreeNode1.Text = "Cadastro Clientes"
        TreeNode1.ToolTipText = "Cadastro de Clientes"
        TreeNode2.Name = "Regiao"
        TreeNode2.Tag = "S"
        TreeNode2.Text = "Região"
        TreeNode2.ToolTipText = "Cadastro de Região"
        TreeNode3.Name = "ClientesVerSaldoCredito"
        TreeNode3.Tag = "S"
        TreeNode3.Text = "Ver Limite de Crédito"
        TreeNode3.ToolTipText = "Verifica o Limite de Crédito do Cliente"
        TreeNode4.Name = "RelClientes"
        TreeNode4.Tag = "S"
        TreeNode4.Text = "Relatório Cliente"
        TreeNode5.Name = "Node9"
        TreeNode5.Tag = "N"
        TreeNode5.Text = "Clientes"
        TreeNode6.Name = "AgendaServico"
        TreeNode6.Tag = "S"
        TreeNode6.Text = "Agenda Serviço e Compromisso"
        TreeNode6.ToolTipText = "Agenda Serviço e Compromisso"
        TreeNode7.Name = "CepLocalizar"
        TreeNode7.Tag = "S"
        TreeNode7.Text = "Consulta de Cep"
        TreeNode7.ToolTipText = "Consulta de Cep"
        TreeNode8.Name = "Fornecedor"
        TreeNode8.Tag = "S"
        TreeNode8.Text = "Cadastro Fornecedor"
        TreeNode8.ToolTipText = "Cadastro Fornecedor"
        TreeNode9.Name = "FornecedorRelatorio"
        TreeNode9.Tag = "S"
        TreeNode9.Text = "Relatório Fornecedor"
        TreeNode9.ToolTipText = "Relatório Fornecedor"
        TreeNode10.Name = "Node4"
        TreeNode10.Text = "Fornecedores"
        TreeNode11.Name = "Produtos"
        TreeNode11.Tag = "S"
        TreeNode11.Text = "Cadastro Produtos"
        TreeNode11.ToolTipText = "Cadastro Produtos"
        TreeNode12.Name = "ProcuraProduto"
        TreeNode12.Tag = "S"
        TreeNode12.Text = "Consulta de Produtos"
        TreeNode12.ToolTipText = "Consulta de Produtos"
        TreeNode13.Name = "ProdutosInativos"
        TreeNode13.Tag = "S"
        TreeNode13.Text = "Produtos Inativos"
        TreeNode13.ToolTipText = "Produtos Inativos"
        TreeNode14.Name = "ProdutoEstoqueConsulta"
        TreeNode14.Tag = "S"
        TreeNode14.Text = "Consulta de Estoque de Produtos"
        TreeNode14.ToolTipText = "Consulta de Estoque de Produtos"
        TreeNode15.Name = "ProdutoEstoqueAtualizar"
        TreeNode15.Tag = "S"
        TreeNode15.Text = "Atualizador Estoque"
        TreeNode15.ToolTipText = "Atualizador Estoque"
        TreeNode16.Name = "ProdutoEstoqueAjuste"
        TreeNode16.Tag = "S"
        TreeNode16.Text = "Ajuste do Estoque"
        TreeNode16.ToolTipText = "Ajuste do Estoque"
        TreeNode17.Name = "AtualizarTributacaoProduto"
        TreeNode17.Tag = "S"
        TreeNode17.Text = "Atualizar Tributação Pis - Cofins Venda"
        TreeNode17.ToolTipText = "Atualizar Tributação Pis - Cofins Venda"
        TreeNode18.Name = "EstoqueTransferencia"
        TreeNode18.Tag = "S"
        TreeNode18.Text = "Tranferência de Estoque (Depósito/Venda)"
        TreeNode18.ToolTipText = "Tranferência de Estoque (Depósito/Venda)"
        TreeNode19.Name = "Grupos"
        TreeNode19.Tag = "S"
        TreeNode19.Text = "Cadastro de Grupos"
        TreeNode19.ToolTipText = "Cadastro de Grupos"
        TreeNode20.Name = "Marcas"
        TreeNode20.Tag = "S"
        TreeNode20.Text = "Cadastro de Marcas"
        TreeNode20.ToolTipText = "Cadastro de Marcas"
        TreeNode21.Name = "Cor"
        TreeNode21.Tag = "S"
        TreeNode21.Text = "Cadastro de Cor"
        TreeNode21.ToolTipText = "Cadastro de Cor"
        TreeNode22.Name = "TipoGrupo"
        TreeNode22.Tag = "S"
        TreeNode22.Text = "Cadastro de Tipo de Grupo"
        TreeNode22.ToolTipText = "Cadastro de Tipo de Grupo"
        TreeNode23.Name = "SubGrupo"
        TreeNode23.Tag = "S"
        TreeNode23.Text = "Cadastro de SubGrupo"
        TreeNode23.ToolTipText = "Cadastro de SubGrupo"
        TreeNode24.Name = "ProdutoLocal"
        TreeNode24.Tag = "S"
        TreeNode24.Text = "Cadastro de Localização"
        TreeNode24.ToolTipText = "Cadastro de Localização"
        TreeNode25.Name = "ProdutoRelat"
        TreeNode25.Tag = "S"
        TreeNode25.Text = "Relatório de Produto"
        TreeNode25.ToolTipText = "Relatório de Produto"
        TreeNode26.Name = "CadGeraisRelat"
        TreeNode26.Tag = "S"
        TreeNode26.Text = "Relatório de Cadastro Gerais"
        TreeNode26.ToolTipText = "Relatório de Cadastro Gerais"
        TreeNode27.Name = "ProdutoSaldoEstoque"
        TreeNode27.Tag = "S"
        TreeNode27.Text = "Saldo de Estoque"
        TreeNode27.ToolTipText = "Saldo de Estoque"
        TreeNode28.Name = "ProdutoEtiquetas"
        TreeNode28.Tag = "S"
        TreeNode28.Text = "Etiquetas de Produto - Cod Barra"
        TreeNode28.ToolTipText = "Etiquetas de Produto - Cod Barra"
        TreeNode29.Name = "Iventario"
        TreeNode29.Tag = "S"
        TreeNode29.Text = "Iventário"
        TreeNode29.ToolTipText = "Iventário"
        TreeNode30.Name = "ProdutoGerarEtiqueta"
        TreeNode30.Tag = "S"
        TreeNode30.Text = "Gerar Etiquetas"
        TreeNode30.ToolTipText = "Gerar Etiquetas"
        TreeNode31.Name = "Node7"
        TreeNode31.Text = "Produtos"
        TreeNode32.Name = "Producao"
        TreeNode32.Tag = "S"
        TreeNode32.Text = "Ordem de Produção"
        TreeNode32.ToolTipText = "Cadastra a Ordem de Produção"
        TreeNode33.Name = "ProducaoEstoqueConfirmar"
        TreeNode33.Tag = "S"
        TreeNode33.Text = "Confirma Ordem de Produção"
        TreeNode33.ToolTipText = "Confirma Ordem de Produção"
        TreeNode34.Name = "Node26"
        TreeNode34.Text = "Produção"
        TreeNode35.Name = "ObejtosCad"
        TreeNode35.Tag = "S"
        TreeNode35.Text = "Cadastro de Objetos(Veículos)"
        TreeNode35.ToolTipText = "Cadastro de Objetos(Veículos)"
        TreeNode36.Name = "ObjetoLocalizarPlaca"
        TreeNode36.Tag = "S"
        TreeNode36.Text = "Localiza Veículos por placa"
        TreeNode36.ToolTipText = "Localiza Veículos por placa"
        TreeNode37.Name = "Servicos"
        TreeNode37.Tag = "S"
        TreeNode37.Text = "Cadastro de Serviços"
        TreeNode37.ToolTipText = "Cadastro de Serviços"
        TreeNode38.Name = "ServicoFuncionario"
        TreeNode38.Tag = "S"
        TreeNode38.Text = "Cadastro de Funcionário e Serviço"
        TreeNode38.ToolTipText = "Cadastro de Funcionário e Serviço"
        TreeNode39.Name = "GrupoServico"
        TreeNode39.Tag = "S"
        TreeNode39.Text = "Cadastro de Grupo de Serviço"
        TreeNode39.ToolTipText = "Cadastro de Grupo de Serviço"
        TreeNode40.Name = "ServicoConsultaPreco"
        TreeNode40.Tag = "S"
        TreeNode40.Text = "Consulta Preço de Serviço"
        TreeNode40.ToolTipText = "Consulta Preço de Serviço"
        TreeNode41.Name = "ServicoListagemAlterarPreco"
        TreeNode41.Tag = "S"
        TreeNode41.Text = "Alteração de Preço de Serviço"
        TreeNode41.ToolTipText = "Alteração de Preço de Serviço"
        TreeNode42.Name = "Node27"
        TreeNode42.Text = "Serviços"
        TreeNode43.Name = "LocalPagamento"
        TreeNode43.Tag = "S"
        TreeNode43.Text = "Cadastro de Local de Pagamento"
        TreeNode43.ToolTipText = "Cadastro de Local de Pagamento"
        TreeNode44.Name = "FormaPgto"
        TreeNode44.Tag = "S"
        TreeNode44.Text = "Condição de Pagamento"
        TreeNode44.ToolTipText = "Condição de Pagamento"
        TreeNode45.Name = "TipoPgto"
        TreeNode45.Tag = "S"
        TreeNode45.Text = "Cadastro de Tipo de Pagamento"
        TreeNode45.ToolTipText = "Cadastro de Tipo de Pagamento"
        TreeNode46.Name = "TipoFormaPgto"
        TreeNode46.Tag = "S"
        TreeNode46.Text = "Anexar Cond. Pgto ao Tipo de Pgto"
        TreeNode46.ToolTipText = "Anexar Cond. Pgto ao Tipo de Pgto"
        TreeNode47.Name = "Cfop"
        TreeNode47.Tag = "S"
        TreeNode47.Text = "Cadastro de Cfop"
        TreeNode47.ToolTipText = "Cadastro de Cfop"
        TreeNode48.Name = "CFOPse"
        TreeNode48.Tag = "S"
        TreeNode48.Text = "Cadastro CFOP Entrada e Saída"
        TreeNode48.ToolTipText = "Cadastro CFOP Entrada e Saída"
        TreeNode49.Name = "Transportadora"
        TreeNode49.Tag = "S"
        TreeNode49.Text = "Cadastro de Transportadora"
        TreeNode49.ToolTipText = "Cadastro de Transportadora"
        TreeNode50.Name = "Node28"
        TreeNode50.Text = "Cadastros Gerais"
        TreeNode51.Name = "Empresa"
        TreeNode51.Tag = "S"
        TreeNode51.Text = "Empresa"
        TreeNode51.ToolTipText = "Cadastro da Empresa"
        TreeNode52.Name = "ExportarNFE"
        TreeNode52.Tag = "S"
        TreeNode52.Text = "Exportação para NFE"
        TreeNode52.ToolTipText = "Exportação para NFE"
        TreeNode53.Name = "ExportPAF"
        TreeNode53.Tag = "S"
        TreeNode53.Text = "Exportação para Paf"
        TreeNode53.ToolTipText = "Exportação para Paf"
        TreeNode54.Name = "ExportPAF2"
        TreeNode54.Tag = "S"
        TreeNode54.Text = "Exporta Paf Exclaim"
        TreeNode54.ToolTipText = "Exporta Paf Exclaim"
        TreeNode55.Name = "ProSoftExport"
        TreeNode55.Tag = "S"
        TreeNode55.Text = "Exporta Prosoft"
        TreeNode55.ToolTipText = "Exporta Prosoft"
        TreeNode56.Name = "Node3"
        TreeNode56.Tag = "N"
        TreeNode56.Text = "Menu Geral"
        TreeNode57.Name = "ReceberProrrogação"
        TreeNode57.Tag = "S"
        TreeNode57.Text = "Prorrogação contas a Receber"
        TreeNode57.ToolTipText = "Prorrogação contas a Receber"
        TreeNode58.Name = "ReceberAlterarLocalPagamento"
        TreeNode58.Tag = "S"
        TreeNode58.Text = "Alterar Local de Pagamento"
        TreeNode58.ToolTipText = "Alterar Local de Pagamento"
        TreeNode59.Name = "ReceberAlterarVencimento"
        TreeNode59.Tag = "S"
        TreeNode59.Text = "Alterar Data de Vencimento"
        TreeNode59.ToolTipText = "Alterar Data de Vencimento"
        TreeNode60.Name = "Receber"
        TreeNode60.Tag = "S"
        TreeNode60.Text = "Consulta/Baixa de Contas a Receber"
        TreeNode60.ToolTipText = "Consulta/Baixa de Contas a Receber"
        TreeNode61.Name = "ReceberBaixaLote"
        TreeNode61.Tag = "S"
        TreeNode61.Text = "Baixa Recebimento em Lote"
        TreeNode61.ToolTipText = "Baixa Recebimento em Lote"
        TreeNode62.Name = "ReceberAgrupar"
        TreeNode62.Tag = "S"
        TreeNode62.Text = "Agrupar Recebimentos"
        TreeNode62.ToolTipText = "Agrupar Recebimentos"
        TreeNode63.Name = "ReceberAvulso"
        TreeNode63.Tag = "S"
        TreeNode63.Text = "A Receber Avulso"
        TreeNode63.ToolTipText = "A Receber Avulso"
        TreeNode64.Name = "ReceberRelat"
        TreeNode64.Tag = "S"
        TreeNode64.Text = "Relatório de Contas a Receber"
        TreeNode64.ToolTipText = "Relatório de Contas a Receber"
        TreeNode65.Name = "ReceberRelatPeriodoValor"
        TreeNode65.Tag = "S"
        TreeNode65.Text = "Contas a Receber no Período e Valor"
        TreeNode65.ToolTipText = "Contas a Receber no Período e Valor"
        TreeNode66.Name = "Pagar"
        TreeNode66.Tag = "S"
        TreeNode66.Text = "Consulta/Baixa de Contas a Pagar"
        TreeNode66.ToolTipText = "Consulta/Baixa de Contas a Pagar"
        TreeNode67.Name = "PagarRelat"
        TreeNode67.Tag = "S"
        TreeNode67.Text = "Relatório de consta a Pagar"
        TreeNode67.ToolTipText = "Relatório de consta a Pagar"
        TreeNode68.Name = "ReciboAvulso"
        TreeNode68.Tag = "S"
        TreeNode68.Text = "Recibo Avulso"
        TreeNode68.ToolTipText = "Recibo Avulso"
        TreeNode69.Name = "DuplicataAvulso"
        TreeNode69.Tag = "S"
        TreeNode69.Text = "Emitir Duplicata Avulso"
        TreeNode69.ToolTipText = "Emitir Duplicata Avulso"
        TreeNode70.Name = "ReimpressaoReciboPagarReceber"
        TreeNode70.Tag = "S"
        TreeNode70.Text = "Reimpressão Recibo Pagar e Receber"
        TreeNode70.ToolTipText = "Reimpressão Recibo Pagar e Receber"
        TreeNode71.Name = "PagarEditar"
        TreeNode71.Tag = "S"
        TreeNode71.Text = "Editar contas a Pagar"
        TreeNode71.ToolTipText = "Editar contas a Pagar"
        TreeNode72.Name = "CartaoCreditoMenu"
        TreeNode72.Tag = "S"
        TreeNode72.Text = "Central Cartão"
        TreeNode72.ToolTipText = "Central Cartão"
        TreeNode73.Name = "pagarparcelamentos"
        TreeNode73.Tag = "S"
        TreeNode73.Text = "Editar Parcelamento Contas a Pagar"
        TreeNode73.ToolTipText = "Editar Parcelamento Contas a Pagar"
        TreeNode74.Name = "Node4"
        TreeNode74.Tag = "N"
        TreeNode74.Text = "Menu Pagar e Receber"
        TreeNode75.Name = "PedidoVendaSenhaItem"
        TreeNode75.Tag = "S"
        TreeNode75.Text = "Senha desconto produto"
        TreeNode75.ToolTipText = "Senha desconto produto"
        TreeNode76.Name = "PedidoVenda"
        TreeNode76.Tag = "S"
        TreeNode76.Text = "Pedido"
        TreeNode76.ToolTipText = "Pedido de Vendas"
        TreeNode77.Name = "PedidoOS"
        TreeNode77.Tag = "S"
        TreeNode77.Text = "Ordem de Serviço"
        TreeNode77.ToolTipText = "Ordem de Serviço"
        TreeNode78.Name = "HistoricoOsPedido"
        TreeNode78.Tag = "S"
        TreeNode78.Text = "Historico Cliente Os Pedido"
        TreeNode78.ToolTipText = "Historico Cliente Os Pedido"
        TreeNode79.Name = "PedidoVendaFaturamento"
        TreeNode79.Tag = "S"
        TreeNode79.Text = "Pesquisa de Pedido"
        TreeNode79.ToolTipText = "Pesquisa de Pedido"
        TreeNode80.Name = "PedidoReImpress"
        TreeNode80.Tag = "S"
        TreeNode80.Text = "Reimpressão de Pedido"
        TreeNode80.ToolTipText = "Reimpressão de Pedido"
        TreeNode81.Name = "PedidoStatusAndamento"
        TreeNode81.Tag = "S"
        TreeNode81.Text = "Acompanhamento de Pedido"
        TreeNode81.ToolTipText = "Acompanhamento de Pedido"
        TreeNode82.Name = "PedidoCancelamento"
        TreeNode82.Tag = "S"
        TreeNode82.Text = "Cancelamento de Pedido"
        TreeNode82.ToolTipText = "Cancelamento de Pedido"
        TreeNode83.Name = "PedidoRelat"
        TreeNode83.Tag = "S"
        TreeNode83.Text = "Relatórios de Pedido"
        TreeNode83.ToolTipText = "Relatórios de Pedido"
        TreeNode84.Name = "OsRelat"
        TreeNode84.Tag = "S"
        TreeNode84.Text = "Relatórios de Pedido OS"
        TreeNode84.ToolTipText = "Relatórios de Pedido OS"
        TreeNode85.Name = "ComissaoRelat"
        TreeNode85.Tag = "S"
        TreeNode85.Text = "Relatório de Comissão Vendedores"
        TreeNode85.ToolTipText = "Relatório de Comissão Vendedores"
        TreeNode86.Name = "Node59"
        TreeNode86.Text = "Relatórios Pedido"
        TreeNode87.Name = "OrdemEmbarqueCancelamento"
        TreeNode87.Tag = "S"
        TreeNode87.Text = "Cancelamento de Ordem de Embarque"
        TreeNode87.ToolTipText = "Cancelamento de Ordem de Embarque"
        TreeNode88.Name = "Orçamento"
        TreeNode88.Tag = "S"
        TreeNode88.Text = "Orçamento"
        TreeNode88.ToolTipText = "Orçamento de Vendas de Peças"
        TreeNode89.Name = "OSorçamento"
        TreeNode89.Tag = "S"
        TreeNode89.Text = "Orçamento de Serviços e Produtos"
        TreeNode89.ToolTipText = "Orçamento de Serviços e Produtos"
        TreeNode90.Name = "NFiscalServiço"
        TreeNode90.Tag = "S"
        TreeNode90.Text = "Nota Fiscal del Serviço"
        TreeNode90.ToolTipText = "Nota Fiscal del Serviço"
        TreeNode91.Name = "NFCFGServiço"
        TreeNode91.Tag = "S"
        TreeNode91.Text = "Configuração de Nota Fiscal de Serviço"
        TreeNode91.ToolTipText = "Configuração de Nota Fiscal de Serviço"
        TreeNode92.Name = "Node66"
        TreeNode92.Text = "Nota Fiscal"
        TreeNode93.Name = "DocumentoEntrada"
        TreeNode93.Tag = "S"
        TreeNode93.Text = "Entrada de Documentos"
        TreeNode93.ToolTipText = "Entrada de Documentos"
        TreeNode94.Name = "Compra"
        TreeNode94.Tag = "S"
        TreeNode94.Text = "Entrada de Estoque"
        TreeNode94.ToolTipText = "Entrada de Estoque"
        TreeNode95.Name = "ComprasRelat"
        TreeNode95.Tag = "S"
        TreeNode95.Text = "Relatórios de NF Compras"
        TreeNode95.ToolTipText = "Relatórios de NF Compras"
        TreeNode96.Name = "Node67"
        TreeNode96.Text = "Entrada"
        TreeNode97.Name = "Node5"
        TreeNode97.Tag = "N"
        TreeNode97.Text = "Menu Movimento"
        TreeNode98.Name = "DocumentoEntrada"
        TreeNode98.Tag = "S"
        TreeNode98.Text = "Documento de Entrada"
        TreeNode98.ToolTipText = "Documento de Entrada"
        TreeNode99.Name = "SellShoesCompra"
        TreeNode99.Tag = "S"
        TreeNode99.Text = "Entrada Nota Fiscal"
        TreeNode99.ToolTipText = "Entrada Nota Fiscal"
        TreeNode100.Name = "SellShoesPedidoCompra"
        TreeNode100.Tag = "S"
        TreeNode100.Text = "Pedido Compra"
        TreeNode100.ToolTipText = "Pedido Compra"
        TreeNode101.Name = "PedCompraFinanceiro"
        TreeNode101.Tag = "S"
        TreeNode101.Text = "Pedido Compra Financeiro"
        TreeNode101.ToolTipText = "Pedido Compra Financeiro"
        TreeNode102.Name = "Menu Movimento Sellshoes"
        TreeNode102.Text = "Menu Movimento Sellshoes"
        TreeNode103.Name = "CaixaAtivarDesativar"
        TreeNode103.Tag = "S"
        TreeNode103.Text = "Ativar e Desativar Caixa"
        TreeNode103.ToolTipText = "Ativar e Desativar Caixa"
        TreeNode104.Name = "Caixa"
        TreeNode104.Tag = "S"
        TreeNode104.Text = "Visualizador do Caixa"
        TreeNode104.ToolTipText = "Visualizador do Caixa"
        TreeNode105.Name = "CaixaRepasseCheque"
        TreeNode105.Tag = "S"
        TreeNode105.Text = "Repasse Cheque Pré do Caixa"
        TreeNode105.ToolTipText = "Repasse Cheque Pré do Caixa"
        TreeNode106.Name = "CaixaLançamentos"
        TreeNode106.Tag = "S"
        TreeNode106.Text = "Lançamentos Caixa"
        TreeNode106.ToolTipText = "Lançamentos Caixa"
        TreeNode107.Name = "ClientesCred"
        TreeNode107.Tag = "S"
        TreeNode107.Text = "Lançamento de Crédito p/Cliente"
        TreeNode107.ToolTipText = "Lançamento de Crédito p/Cliente"
        TreeNode108.Name = "ImprimirDuplicataNP"
        TreeNode108.Tag = "S"
        TreeNode108.Text = "Impressão de  NP/Duplicata do Pedido"
        TreeNode108.ToolTipText = "Impressão de  NP/Duplicata do Pedido"
        TreeNode109.Name = "RecebidaVoltar"
        TreeNode109.Tag = "S"
        TreeNode109.Text = "Estorno Recebimento"
        TreeNode109.ToolTipText = "Estorno Recebimento"
        TreeNode110.Name = "PagasVoltar"
        TreeNode110.Tag = "S"
        TreeNode110.Text = "Estorno de Pagamento"
        TreeNode110.ToolTipText = "Estorno de Pagamento"
        TreeNode111.Name = "CaixaRelat"
        TreeNode111.Tag = "S"
        TreeNode111.Text = "Relatório"
        TreeNode111.ToolTipText = "Relatório"
        TreeNode112.Name = "BalanceteCadastro"
        TreeNode112.Tag = "S"
        TreeNode112.Text = "Cadastro de Conta Balancete"
        TreeNode112.ToolTipText = "Cadastro de Conta Balancete"
        TreeNode113.Name = "ResultadosContas"
        TreeNode113.Tag = "S"
        TreeNode113.Text = "Cadastro de Conta Resultado"
        TreeNode113.ToolTipText = "Cadastro de Conta Resultado"
        TreeNode114.Name = "MostrarContasInativas"
        TreeNode114.Tag = "S"
        TreeNode114.Text = "Mostrar Contas Resultado Inativas"
        TreeNode114.ToolTipText = "Mostrar Contas Resultado Inativas"
        TreeNode115.Name = "BalanceteAlterarLancamento"
        TreeNode115.Tag = "S"
        TreeNode115.Text = "Reclassificar Contas"
        TreeNode115.ToolTipText = "Reclassificar Contas"
        TreeNode116.Name = "BalanceteOrcamentarioRelat"
        TreeNode116.Tag = "S"
        TreeNode116.Text = "Relatórios"
        TreeNode116.ToolTipText = "Relatórios"
        TreeNode117.Name = "Node9"
        TreeNode117.Text = "Balancete Orçamentário"
        TreeNode118.Name = "BancosCad"
        TreeNode118.Tag = "S"
        TreeNode118.Text = "Cadastro de Bancos"
        TreeNode118.ToolTipText = "Cadastro de Bancos"
        TreeNode119.Name = "BancosContaCorrente"
        TreeNode119.Tag = "S"
        TreeNode119.Text = "Cadastro Conta Corrente"
        TreeNode119.ToolTipText = "Cadastro Conta Corrente"
        TreeNode120.Name = "Node12"
        TreeNode120.Text = "Conta Corrente/Bancos"
        TreeNode121.Name = "BancoVisualizador"
        TreeNode121.Tag = "S"
        TreeNode121.Text = "Central de Conta Corrente"
        TreeNode121.ToolTipText = "Central de Conta Corrente"
        TreeNode122.Name = "BancoLançamento"
        TreeNode122.Tag = "S"
        TreeNode122.Text = "Lançamento Banco"
        TreeNode122.ToolTipText = "Lançamento Banco"
        TreeNode123.Name = "BancosContaCorrente"
        TreeNode123.Tag = "S"
        TreeNode123.Text = "Conta Corrente"
        TreeNode123.ToolTipText = "Conta Corrente"
        TreeNode124.Name = "BancoExtrato"
        TreeNode124.Tag = "S"
        TreeNode124.Text = "Extrato Banco"
        TreeNode124.ToolTipText = "Extrato Banco"
        TreeNode125.Name = "BancoCompensar"
        TreeNode125.Tag = "S"
        TreeNode125.Text = "Compensar Cheque"
        TreeNode125.ToolTipText = "Compensar Cheque"
        TreeNode126.Name = "ChequePreClientes"
        TreeNode126.Tag = "S"
        TreeNode126.Text = "Cheque-Pré - Clientes"
        TreeNode126.ToolTipText = "Cheque-Pré - Clientes"
        TreeNode127.Name = "Chequepredevolver"
        TreeNode127.Tag = "S"
        TreeNode127.Text = "Cheque-Pré - Devolvidos"
        TreeNode127.ToolTipText = "Cheque-Pré - Devolvidos"
        TreeNode128.Name = "ChequePreRelat"
        TreeNode128.Tag = "S"
        TreeNode128.Text = "Relatórios Cheque Pré"
        TreeNode128.ToolTipText = "Relatórios Cheque Pré"
        TreeNode129.Name = "Contrato"
        TreeNode129.Tag = "S"
        TreeNode129.Text = "Contrato"
        TreeNode129.ToolTipText = "Contrato"
        TreeNode130.Name = "Node6"
        TreeNode130.Tag = "N"
        TreeNode130.Text = "Menu Caixa e Banco"
        TreeNode131.Name = "Funcionarios"
        TreeNode131.Tag = "S"
        TreeNode131.Text = "Funcionários"
        TreeNode131.ToolTipText = "Funcionários"
        TreeNode132.Name = "FuncionarioCartao"
        TreeNode132.Tag = "S"
        TreeNode132.Text = "Cartão de Funcionário"
        TreeNode132.ToolTipText = "Cartão de Funcionário"
        TreeNode133.Name = "Departamentos"
        TreeNode133.Tag = "S"
        TreeNode133.Text = "Departamentos"
        TreeNode133.ToolTipText = "Departamentos"
        TreeNode134.Name = "Profissao"
        TreeNode134.Tag = "S"
        TreeNode134.Text = "Cadastro de Profissão"
        TreeNode134.ToolTipText = "Cadastro de Profissão"
        TreeNode135.Name = "FuncionariosRelat"
        TreeNode135.Tag = "S"
        TreeNode135.Text = "Funcionários"
        TreeNode135.ToolTipText = "Relatório de Funcionários"
        TreeNode136.Name = "RelDepartamentos"
        TreeNode136.Tag = "S"
        TreeNode136.Text = "Departamentos"
        TreeNode136.ToolTipText = "Relatório de Departamentos"
        TreeNode137.Name = "RelProfissão"
        TreeNode137.Tag = "S"
        TreeNode137.Text = "Profissão"
        TreeNode137.ToolTipText = "Relatório de Profissão"
        TreeNode138.Name = "Node0"
        TreeNode138.Text = "Relatorios de Funcionários"
        TreeNode139.Name = "Node7"
        TreeNode139.Tag = "N"
        TreeNode139.Text = "Menu RH"
        TreeNode140.Name = "Permissoes"
        TreeNode140.Tag = "S"
        TreeNode140.Text = "Permissões"
        TreeNode140.ToolTipText = "Cadastro de Permissões"
        TreeNode141.Name = "PermissaoGetPost"
        TreeNode141.Tag = "S"
        TreeNode141.Text = "Gerenciador de Permissões"
        TreeNode141.ToolTipText = "Gerenciador de Permissões"
        TreeNode142.Name = "Auditor"
        TreeNode142.Tag = "S"
        TreeNode142.Text = "Auditoria"
        TreeNode142.ToolTipText = "Auditoria"
        TreeNode143.Name = "UserSenha"
        TreeNode143.Tag = "S"
        TreeNode143.Text = "UserSenha"
        TreeNode143.ToolTipText = "Cadastro de Senha de Usuário"
        TreeNode144.Name = "CaixaCadastro"
        TreeNode144.Tag = "S"
        TreeNode144.Text = "Cadastro de Caixa"
        TreeNode144.ToolTipText = "Cadastro de Caixa"
        TreeNode145.Name = "CaixasAbertos"
        TreeNode145.Tag = "S"
        TreeNode145.Text = "Caixa em Aberto"
        TreeNode145.ToolTipText = "Caixa em Aberto"
        TreeNode146.Name = "DiaAbrirFechar"
        TreeNode146.Tag = "S"
        TreeNode146.Text = "Criar e Fechar Dia de Trabalho"
        TreeNode146.ToolTipText = "Criar e Fechar Dia de Trabalho"
        TreeNode147.Name = "CodigoSegurança"
        TreeNode147.Tag = "S"
        TreeNode147.Text = "Gerar Código de Segurança do Dia"
        TreeNode147.ToolTipText = "Gerar Código de Segurança do Dia"
        TreeNode148.Name = "Cfg"
        TreeNode148.Tag = "S"
        TreeNode148.Text = "Configuração do Banco de Dados (Alternar)"
        TreeNode148.ToolTipText = "Configuração do Banco de Dados (Alternar)"
        TreeNode149.Name = "AtTabelas"
        TreeNode149.Tag = "S"
        TreeNode149.Text = "Atualizar Tabelas"
        TreeNode149.ToolTipText = "Atualizar Tabelas"
        TreeNode150.Name = "Sobre"
        TreeNode150.Text = "Sobre"
        TreeNode150.ToolTipText = "Sobre"
        TreeNode151.Name = "Node8"
        TreeNode151.Tag = "N"
        TreeNode151.Text = "Menu Configurações"
        TreeNode152.Name = "Node0"
        TreeNode152.Text = "----------------------------------"
        TreeNode153.Name = "RelSellShoesPendenciaCliente"
        TreeNode153.Tag = "S"
        TreeNode153.Text = "Ver Pendências"
        TreeNode153.ToolTipText = "Ver Pendências"
        TreeNode154.Name = "RelSellShoesPedidosTop"
        TreeNode154.Tag = "S"
        TreeNode154.Text = "Ver Ultimas Vendas"
        TreeNode154.ToolTipText = "Ver Ultimas Vendas"
        TreeNode155.Name = "SellShoesClientesProcura"
        TreeNode155.Tag = "S"
        TreeNode155.Text = "Pesquisa de Cliente"
        TreeNode155.ToolTipText = "Pesquisa de Cliente"
        TreeNode156.Name = "SellShoesProdutoProcura"
        TreeNode156.Tag = "S"
        TreeNode156.Text = "Pesquisa de Produto"
        TreeNode156.ToolTipText = "Pesquisa de Produto"
        TreeNode157.Name = "SellShoesReimpressao"
        TreeNode157.Tag = "S"
        TreeNode157.Text = "Reimpressão Pedido"
        TreeNode157.ToolTipText = "Reimpressão Pedido"
        TreeNode158.Name = "SellShoesAutenticacao"
        TreeNode158.Tag = "S"
        TreeNode158.Text = "Vendas"
        TreeNode158.ToolTipText = "Vendas"
        TreeNode159.Name = "SellShoesDevolucao"
        TreeNode159.Tag = "S"
        TreeNode159.Text = "Devolução"
        TreeNode159.ToolTipText = "Devolução"
        TreeNode160.Name = "SellShoesOrcamentoProcura"
        TreeNode160.Tag = "S"
        TreeNode160.Text = "Orçamento"
        TreeNode160.ToolTipText = "Orçamento"
        TreeNode161.Name = "CaixaAtivarDesativar"
        TreeNode161.Tag = "S"
        TreeNode161.Text = "Inicira Caixa"
        TreeNode161.ToolTipText = "Inicira Caixa"
        TreeNode162.Name = "Caixa"
        TreeNode162.Tag = "S"
        TreeNode162.Text = "Vizualizar Caixa"
        TreeNode162.ToolTipText = "Vizualizar Caixa"
        TreeNode163.Name = "SellShoesPendentes"
        TreeNode163.Tag = "S"
        TreeNode163.Text = "Finalizar Vendas"
        TreeNode163.ToolTipText = "Finalizar Vendas"
        TreeNode164.Name = "Receber"
        TreeNode164.Tag = "S"
        TreeNode164.Text = "Recebimento"
        TreeNode164.ToolTipText = "Recebimento"
        TreeNode165.Name = "ReceberBaixaLote"
        TreeNode165.Tag = "S"
        TreeNode165.Text = "Recebimento em Lote"
        TreeNode165.ToolTipText = "Recebimento em Lote"
        TreeNode166.Name = "SellShoesResumoVenda"
        TreeNode166.Tag = "S"
        TreeNode166.Text = "Resumo de Vendas"
        TreeNode166.ToolTipText = "Resumo de Vendas"
        TreeNode167.Name = "Node1"
        TreeNode167.Text = "Auxiliar SellShoes"
        TreeNode168.Name = "PedidoVendaSenhaItem"
        TreeNode168.Tag = "S"
        TreeNode168.Text = "Permissão desc. Vendas"
        TreeNode168.ToolTipText = "Permissão desc. Vendas"
        TreeNode169.Name = "BancoCompensar"
        TreeNode169.Tag = "S"
        TreeNode169.Text = "Banco Compensar"
        TreeNode169.ToolTipText = "Banco Compensar"
        TreeNode170.Name = "CodigoSegurancaInformar"
        TreeNode170.Tag = "S"
        TreeNode170.Text = "Codigo de Segurança"
        TreeNode170.ToolTipText = "Informar código de Segurança"
        TreeNode171.Name = "Menu Interno"
        TreeNode171.Text = "Menu Interno"
        TreeNode172.Name = "Permissao"
        TreeNode172.Text = "Permissão"
        Me.ListaPermissao.Nodes.AddRange(New System.Windows.Forms.TreeNode() {TreeNode172})
        Me.ListaPermissao.Size = New System.Drawing.Size(459, 378)
        Me.ListaPermissao.TabIndex = 0
        '
        'MenuAdicional
        '
        Me.MenuAdicional.Items.AddRange(New System.Windows.Forms.ToolStripItem() {Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem})
        Me.MenuAdicional.Name = "MenuAdicional"
        Me.MenuAdicional.Size = New System.Drawing.Size(249, 26)
        '
        'AddPermissãoGrupoDeUsuárioToolStripMenuItem
        '
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem.Name = "AddPermissãoGrupoDeUsuárioToolStripMenuItem"
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem.Size = New System.Drawing.Size(248, 22)
        Me.AddPermissãoGrupoDeUsuárioToolStripMenuItem.Text = "Add Permissão Grupo de Usuário"
        '
        'HelpProvider1
        '
        Me.HelpProvider1.HelpNamespace = "C:\UpSistemas\Help\dblsistemas.chm"
        '
        'Permissoes
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(7.0!, 15.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(481, 426)
        Me.ControlBox = False
        Me.Controls.Add(Me.PanelEx1)
        Me.Font = New System.Drawing.Font("Comic Sans MS", 8.25!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow
        Me.HelpProvider1.SetHelpNavigator(Me, System.Windows.Forms.HelpNavigator.KeywordIndex)
        Me.Name = "Permissoes"
        Me.HelpProvider1.SetShowHelp(Me, True)
        Me.ShowInTaskbar = False
        Me.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen
        Me.Text = "Permissoes - T191"
        Me.PanelEx1.ResumeLayout(False)
        Me.MenuAdicional.ResumeLayout(False)
        Me.ResumeLayout(False)

    End Sub
    Friend WithEvents PanelEx1 As DevComponents.DotNetBar.PanelEx
    Friend WithEvents ListaPermissao As System.Windows.Forms.TreeView
    Friend WithEvents btFechar As DevComponents.DotNetBar.ButtonX
    Friend WithEvents MenuAdicional As System.Windows.Forms.ContextMenuStrip
    Friend WithEvents AddPermissãoGrupoDeUsuárioToolStripMenuItem As System.Windows.Forms.ToolStripMenuItem
    Friend WithEvents HelpProvider1 As System.Windows.Forms.HelpProvider
    Friend WithEvents btCopiarDe As DevComponents.DotNetBar.ButtonX
End Class
